export type NodeSupportLevel = 'full' | 'partial' | 'import-only' | 'unsupported';

export interface NodeTypeConfig {
  type: string;
  displayName: string;
  category: 'trigger' | 'action' | 'logic' | 'integration';
  supportLevel: NodeSupportLevel;
  description: string;
  icon: string;
  color: string;
  inputs: number;
  outputs: number;
  defaultParameters: Record<string, unknown>;
}

export const NODE_TYPES = {
  CODE: 'n8n-nodes-base.code',
  HTTP_REQUEST: 'n8n-nodes-base.httpRequest',
  IF: 'n8n-nodes-base.if',
  SWITCH: 'n8n-nodes-base.switch',
  MERGE: 'n8n-nodes-base.merge',
  SPLIT_IN_BATCHES: 'n8n-nodes-base.splitInBatches',
  NO_OP: 'n8n-nodes-base.noOp',
  WEBHOOK: 'n8n-nodes-base.webhook',
  RESPOND_TO_WEBHOOK: 'n8n-nodes-base.respondToWebhook',
  SCHEDULE_TRIGGER: 'n8n-nodes-base.scheduleTrigger',
  EMAIL_SEND: 'n8n-nodes-base.emailSend',
  GOOGLE_SHEETS: 'n8n-nodes-base.googleSheets',
  GOOGLE_DRIVE: 'n8n-nodes-base.googleDrive',
  GOOGLE_DRIVE_TRIGGER: 'n8n-nodes-base.googleDriveTrigger',
  GOOGLE_DOCS: 'n8n-nodes-base.googleDocs',
  SLACK: 'n8n-nodes-base.slack',
  TWITTER: 'n8n-nodes-base.twitter',
} as const;

export const NODE_TYPE_CONFIGS: Record<string, NodeTypeConfig> = {
  [NODE_TYPES.CODE]: {
    type: NODE_TYPES.CODE,
    displayName: 'Code',
    category: 'action',
    supportLevel: 'full',
    description: 'Execute custom JavaScript code',
    icon: 'Code',
    color: '#ff6d5a',
    inputs: 1,
    outputs: 1,
    defaultParameters: { jsCode: '// Write your code here\nreturn items;', mode: 'runOnceForAllItems' },
  },
  [NODE_TYPES.HTTP_REQUEST]: {
    type: NODE_TYPES.HTTP_REQUEST,
    displayName: 'HTTP Request',
    category: 'action',
    supportLevel: 'full',
    description: 'Make HTTP requests to any API',
    icon: 'Globe',
    color: '#0ea5e9',
    inputs: 1,
    outputs: 1,
    defaultParameters: { method: 'GET', url: '', authentication: 'none' },
  },
  [NODE_TYPES.IF]: {
    type: NODE_TYPES.IF,
    displayName: 'IF',
    category: 'logic',
    supportLevel: 'full',
    description: 'Route items based on conditions',
    icon: 'GitBranch',
    color: '#f59e0b',
    inputs: 1,
    outputs: 2,
    defaultParameters: { conditions: { string: [] } },
  },
  [NODE_TYPES.SWITCH]: {
    type: NODE_TYPES.SWITCH,
    displayName: 'Switch',
    category: 'logic',
    supportLevel: 'full',
    description: 'Route items to different outputs based on conditions',
    icon: 'ArrowLeftRight',
    color: '#f59e0b',
    inputs: 1,
    outputs: 4,
    defaultParameters: { rules: { values: [] } },
  },
  [NODE_TYPES.MERGE]: {
    type: NODE_TYPES.MERGE,
    displayName: 'Merge',
    category: 'logic',
    supportLevel: 'full',
    description: 'Merge data from multiple inputs',
    icon: 'Merge',
    color: '#a855f7',
    inputs: 2,
    outputs: 1,
    defaultParameters: { mode: 'append' },
  },
  [NODE_TYPES.SPLIT_IN_BATCHES]: {
    type: NODE_TYPES.SPLIT_IN_BATCHES,
    displayName: 'Split In Batches',
    category: 'logic',
    supportLevel: 'full',
    description: 'Process items in batches',
    icon: 'Layers',
    color: '#a855f7',
    inputs: 1,
    outputs: 2,
    defaultParameters: { batchSize: 10 },
  },
  [NODE_TYPES.NO_OP]: {
    type: NODE_TYPES.NO_OP,
    displayName: 'No Operation',
    category: 'logic',
    supportLevel: 'full',
    description: 'Pass through data unchanged',
    icon: 'MinusCircle',
    color: '#6b7280',
    inputs: 1,
    outputs: 1,
    defaultParameters: {},
  },
  [NODE_TYPES.WEBHOOK]: {
    type: NODE_TYPES.WEBHOOK,
    displayName: 'Webhook',
    category: 'trigger',
    supportLevel: 'full',
    description: 'Start workflow on HTTP request',
    icon: 'Webhook',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultParameters: { httpMethod: 'POST', path: '', responseMode: 'onReceived' },
  },
  [NODE_TYPES.RESPOND_TO_WEBHOOK]: {
    type: NODE_TYPES.RESPOND_TO_WEBHOOK,
    displayName: 'Respond to Webhook',
    category: 'action',
    supportLevel: 'full',
    description: 'Send response to webhook caller',
    icon: 'Reply',
    color: '#10b981',
    inputs: 1,
    outputs: 0,
    defaultParameters: { respondWith: 'json', responseBody: '{}', statusCode: 200 },
  },
  [NODE_TYPES.SCHEDULE_TRIGGER]: {
    type: NODE_TYPES.SCHEDULE_TRIGGER,
    displayName: 'Schedule Trigger',
    category: 'trigger',
    supportLevel: 'full',
    description: 'Run workflow on a schedule',
    icon: 'Clock',
    color: '#10b981',
    inputs: 0,
    outputs: 1,
    defaultParameters: { rule: { interval: [{ field: 'hours', minutesInterval: 24 }] } },
  },
  [NODE_TYPES.EMAIL_SEND]: {
    type: NODE_TYPES.EMAIL_SEND,
    displayName: 'Send Email',
    category: 'integration',
    supportLevel: 'partial',
    description: 'Send emails via SMTP',
    icon: 'Mail',
    color: '#ef4444',
    inputs: 1,
    outputs: 1,
    defaultParameters: { fromEmail: '', toEmail: '', subject: '', text: '' },
  },
  [NODE_TYPES.GOOGLE_SHEETS]: {
    type: NODE_TYPES.GOOGLE_SHEETS,
    displayName: 'Google Sheets',
    category: 'integration',
    supportLevel: 'partial',
    description: 'Read/write Google Sheets',
    icon: 'Table',
    color: '#34a853',
    inputs: 1,
    outputs: 1,
    defaultParameters: { operation: 'read', sheetId: '' },
  },
  [NODE_TYPES.GOOGLE_DRIVE]: {
    type: NODE_TYPES.GOOGLE_DRIVE,
    displayName: 'Google Drive',
    category: 'integration',
    supportLevel: 'partial',
    description: 'Manage Google Drive files',
    icon: 'HardDrive',
    color: '#4285f4',
    inputs: 1,
    outputs: 1,
    defaultParameters: { operation: 'list', folderId: '' },
  },
  [NODE_TYPES.GOOGLE_DRIVE_TRIGGER]: {
    type: NODE_TYPES.GOOGLE_DRIVE_TRIGGER,
    displayName: 'Google Drive Trigger',
    category: 'trigger',
    supportLevel: 'partial',
    description: 'Trigger on Google Drive file changes',
    icon: 'HardDrive',
    color: '#4285f4',
    inputs: 0,
    outputs: 1,
    defaultParameters: { event: 'fileCreated', folderId: '' },
  },
  [NODE_TYPES.GOOGLE_DOCS]: {
    type: NODE_TYPES.GOOGLE_DOCS,
    displayName: 'Google Docs',
    category: 'integration',
    supportLevel: 'partial',
    description: 'Create/edit Google Docs',
    icon: 'FileText',
    color: '#4285f4',
    inputs: 1,
    outputs: 1,
    defaultParameters: { operation: 'create', title: '' },
  },
  [NODE_TYPES.SLACK]: {
    type: NODE_TYPES.SLACK,
    displayName: 'Slack',
    category: 'integration',
    supportLevel: 'partial',
    description: 'Send Slack messages',
    icon: 'MessageSquare',
    color: '#4a154b',
    inputs: 1,
    outputs: 1,
    defaultParameters: { resource: 'message', operation: 'post', channel: '', text: '' },
  },
  [NODE_TYPES.TWITTER]: {
    type: NODE_TYPES.TWITTER,
    displayName: 'Twitter / X',
    category: 'integration',
    supportLevel: 'partial',
    description: 'Post tweets and manage Twitter',
    icon: 'Twitter',
    color: '#1da1f2',
    inputs: 1,
    outputs: 1,
    defaultParameters: { resource: 'tweet', operation: 'create', text: '' },
  },
};

export function getNodeSupportLevel(type: string): NodeSupportLevel {
  return NODE_TYPE_CONFIGS[type]?.supportLevel ?? 'unsupported';
}

export function getNodeConfig(type: string): NodeTypeConfig | undefined {
  return NODE_TYPE_CONFIGS[type];
}
